### ISSUE TITLE
Explain how to build/preview locally

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/new-lesson-example#21]

**Comment by wking** [comment]
Is this:

  $ gem install jekyll
  $ make site

(or ‘make serve’)?

**Comment by gvwilson** [comment]
`make serve` runs a local server (which is necessary for loading 
favicon, glyphicons, etc.); I need to document the steps to get Ruby, 
Gem, and Jekyll installed on various platforms.

**Comment by wking** [comment]
On Fri, Apr 29, 2016 at 02:05:21PM -0700, Greg Wilson wrote:
> `make serve` runs a local server (which is necessary for loading 
> favicon, glyphicons, etc.).

That seems like too much trouble for a static site.  Can't we just use
‘root’ and relative links?

**Comment by gvwilson** [comment]
That was what I originally thought, but it hasn't been any trouble at 
all in practice.

**Comment by wking** [comment]
On Fri, Apr 29, 2016 at 04:15:18PM -0700, Greg Wilson wrote:
> That was what I originally thought, but it hasn't been any trouble at 
> all in practice.

‘root’ doesn't seem like much trouble in practice either
(swcarpentry/workshop-template#208), and it allows you to dispense
with the site.domain (which otherwise needs to be tweaked by users).

**Comment by gvwilson** [comment]
Brief explanation added in 9a9cbcd.
