### ISSUE TITLE
Feedback from maintainers

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/new-lesson-example#25]
We will use this issue to collect feedback from maintainers about the current draft of the template.

**Comment by orchid00** [comment]
Could we change the colour of the box at the beginning of each lesson? like a blue or green ?
Also I think the timings should be always more than 0 min.

**Comment by hdashnow** [comment]
It looks great!

Apologies if I've missed discussion on this:
In the index page I would prefer to have the timings of each lesson displayed (10 minutes), rather than a schedule (9am). Individual workshops will obviously vary in when they start, break times, order of content etc, making this schedule of limited use. A schedule seems more appropriate for individual workshop pages rather than the lesson pages.

**Comment by cmacdonell** [comment]
There are several links in http://gvwilson.github.io/new-lesson-example/01-tooling/ that point to https://github.com/gvwilson/new-lesson-template.  But that repo doesn't exist.

**Comment by gvwilson** [comment]
Thanks - fixing.

**Comment by tbekolay** [comment]
Looked at this in more detail today in preparation for the meeting.

- Overall this looks great, definitely an improvement over the current template!
- I'm a bit conflicted on the syntax highlighting... I feel like it would be nice to do it, but I do appreciate that things looking different can be confusing. Perhaps this could be something that could be enabled or disabled in `_config.yml`? Novice lessons should have it disabled, but perhaps in intermediate+ lessons we could enable it.
- The terminology "episode" is new to me. What's the origin, and is there a good analogy between what we expect each "episode" to contain and some other use of the word episode?

Something that would be on my wishlist for improvements would be to add an "Edit this page on Github" link somewhere inconspicuous to make contributing minor changes easier/faster. [Example here](http://compneuro.uwaterloo.ca/meetings.html) (see the Github logo at the top right).
