### ISSUE TITLE
Feedback from non-maintainers

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [gvwilson/new-lesson-example#26]
Following on from an "orthognal" discussion that grew out of

https://github.com/swcarpentry/shell-extras/pull/36

I'd just like to throw my thr'pen'th in and suggest that there's no real need for
a "menu" at the top of these pages.

All of the episode menu item links below the Episode menu title will already
be on display in the Schedule (which looks nice!) so why duplicate them in 
a menu? 

Removing that duplication leaves the Extras menu as the only real "menu"
in that top bar, and, I'd further suggest, it would not be that hard to have the 
menu item links below Exras, such as they are, displayed in a line akin  to 
the Source/License/Contact links that appear in the Copyright line.

As I say though, just my 3d.

**Comment by pitviper6** [comment]
As a total DC newbie, I find the template really clean and easy to comprehend at a glance.
