### ISSUE TITLE
Use divs or blockquotes for exercises?

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/new-lesson-example#29]
The template currently uses indented blocks for exercises:

    > ## Title
    > body
    {: .challenge}

Should we instead use `div` elements?

    <div class="challenge">
    ## Title
    body
    </div>

The advantage of blockquotes is consistency with other special items (like setup instructions). The advantages of `div`s are:

1.  Using `>` to indent a long exercise including nested code and output chunks is wearying.
2.  We can easily nest solutions inside those `div`s as well - there's no obvious easy way to nest solutions inside blockquoted exercises.  (We can double-indent, but that's *really* painful, and having them float after the exercise makes associating solutions to exercises programmatically a bit difficult.)

One *disadvantage* of the `div` approach is that Markdown inside HTML is tricky, and sometimes requires `markdown="1"` or something similar to work (see http://kramdown.gettalong.org/syntax.html#html-blocks).

Thoughts?

**Comment by shwina** [comment]
I'm for the consistency of blockquotes, and I think that an indented solution would actually look rather nice. Can I ask why double-indent is painful here?

**Comment by gvwilson** [comment]
Try writing up an exercise with two solutions where the exercise has to 
be indented with '>', both of the solutions have to be double-indented, 
and all of them contain code blocks. It's a hell of a lot of typing, and 
hard to read as source text.

**Comment by qjcg** [comment]
My vote goes to the `div` approach, as the two advantages raised above are significant wins.

Markdown is great for marking up text for conversion to HTML for a subset of very common elements, but is not intended to handle all HTML elements & use cases. I'm all for Markdown with straightforward inline-HTML where it simplifies the markup overall.

**Comment by gdevenyi** [comment]
How does a div change impact possible future tool updates/changes?

Do we risk having to change it back?

**Comment by mikej888** [comment]
I'd vote for blockquotes too as I don't like seeing HTML in MarkDown. I don't think using '>' or '>>' is particularly unreadable, so long as sentences aren't wrapped across multiple lines.

A regexp-search-and-replace (supported by Atom or Emacs for example) on the start of a line can insert the '>'s or '>>'s afterwards.

**Comment by qjcg** [comment]
@gdevenyi: It seems unlikely as inline HTML is a core aspect of the markdown format and philosophy.

From the [original markdown website](http://daringfireball.net/projects/markdown/syntax#html):

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML tags. The idea is not to create a syntax that makes it easier to insert HTML tags. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a publishing format; Markdown is a writing format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

**Comment by tbekolay** [comment]
My vote is for blockquotes because my instinct (from doing webdev stuff) is to indent things within div tags for clarity anyhow, which means that there's a chance that we'll have a mix of people indenting within the div and people not indenting within the div. I prefer the explicitness of `> >`, and I think it just looks nicer not to have any HTML in markdown if we can avoid it.

**Comment by gvwilson** [comment]
I similarly dislike mixing HTML and Markdown (not least because edge 
cases confuse parsers in ways that authors find difficult to decipher), 
but how then do we handle solutions to exercises? Zero or more solution 
blocks following an exercise block (i.e., they just happen to be 
adjacent)? Or nesting zero or more solution blockquotes inside an 
exercise blockquote (which gets really ugly, really quickly)?

**Comment by gvwilson** [comment]
I have added an example to show what formatting challenges with `div` will look like at:

https://raw.githubusercontent.com/gvwilson/new-lesson-example/gh-pages/_episodes/04-divs.md

which is rendered at:

http://gvwilson.github.io/new-lesson-example/04-divs/

**Comment by qjcg** [comment]
LGTM, but I think everyone here probably already knew that. ;)

The div block could potentially be offset with an extra newline or two for enhanced readability if desired.

**Comment by orchid00** [comment]
I vote for not using HTML with markdown. By experience this doesn't always work so it is better not to mix them.
I'll suggest to create a colour palette. The example has some strange rainbow colours, what that intentional? or just for the sake of an example?

**Comment by gvwilson** [comment]
The colors are intentional, and taken from a recommended web color 
palette.  Pull requests are welcome - you can experiment with changes by 
modifying lines lines 72-79 of assets/css/lessons.scss.

**Comment by gvwilson** [comment]
It looks like we're going with separate blockquotes for solutions (i.e., not nested), so that we can make them clickable for show/hide.
