### ISSUE TITLE
Use a better color palette

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/new-lesson-example#31]
The colors for blockquotes aren't universally loved - someone should pick a better palette.  See line 72++ of assets/css/lesson.scss.

**Comment by orchid00** [comment]
Here are some suggestion: we could add this to vote?
1) facebook colour palette http://www.color-hex.com/color-palette/185 Blue is trust and it is also the colour of the swc logo
2) werkpress colour palette https://au.pinterest.com/pin/126663808244351516/ offer some contrast
3) twitter palette: http://www.color-hex.com/color-palette/1160 also in the scale of blues
4) giant goldfish: http://www.colourlovers.com/palette/92095/Giant_Goldfish seems to be a lovable colour palette in new sites

**Comment by gvwilson** [comment]
Thanks for this - we'll need eight distinct colors, so can you please 
pick your favorite and PR color codes in assets/css/lessons.scss ?

**Comment by gvwilson** [comment]
The template now uses an 'autumn' color palette (see files/autumn.jpg) for Software Carpentry:

![screen shot 2016-05-28 at 7 56 08 am](https://cloud.githubusercontent.com/assets/911566/15627186/142f04d4-24aa-11e6-8ed6-ccd1b7ce3a74.png)

and a 'spring' color palette (see files/spring.jpg) for Data Carpentry:

![screen shot 2016-05-28 at 7 55 38 am](https://cloud.githubusercontent.com/assets/911566/15627189/20fa7784-24aa-11e6-86d6-24e94502c459.png)

This (and the logo) can be changed by editing the value of 'carpentry' in `_config.yml`.

**Comment by tbekolay** [comment]
The autumn colors are rather dark compared to the spring palette... might the text in the callout header be more readable in white?

**Comment by gvwilson** [comment]
Yeah, tried that - uuuuugly.  Should we use the spring palette for both 
carpentries?

**Comment by tbekolay** [comment]
Spring looks pretty nice so using it for both sounds good to me :) The logo still differentiates them if that's a concern!

**Comment by orchid00** [comment]
I vote to have the same palette for SWC and DC :)

**Comment by gvwilson** [comment]
And which is your preference?

**Comment by orchid00** [comment]
Neither autumn nor Spring. I will go for this http://www.colourlovers.com/palette/92095/Giant_Goldfish adding three tones of blue. I haven't got the time to test it on CSS

**Comment by orchid00** [comment]
This is a new suggestion: 
![suggestion](https://cloud.githubusercontent.com/assets/9795785/15735805/cbe3dea0-28de-11e6-895d-93e3cb7d4e70.png)

It needs changes on lessons.scss

// blockquotes

{% if site.carpentry == "swc" %}
$color-callout:     #80abcf !default;
$color-challenge:   #69d2e7 !default;
$color-checklist:   #f38630 !default;
$color-keypoints:   #fa6c07 !default;
$color-objectives:  #14a3c7 !default;
$color-prereq:      #a7d9d5 !default;
$color-solution:    #e0e4cc !default;
$color-testimonial: #d99600 !default;
{% endif %}

Feel free to use it if you like

**Comment by gvwilson** [comment]
Nice - thanks very much.
